### ISSUE TITLE
General use questions and remarks

### ISSUE THREAD

**Issue by IgorPietraszko** [referbruv/CognitoUserManager#3]
Thanks for the code and the article - very useful.  You've earned a cup of coffee!!!  I got some questions:

1) If you/one is planning to run the back-end in an AWS Lambda, why use the SRP and not the Admin flow?
2) In the section "Prerequisites for Accessing AWS Cognito Resources" you state "In case if we're not deploying our application inside an AWS environment we'd also require the credentials of a user who has all the required permissions for accessing the Cognito user pool.".  If running in an AWS Lambda, would that piggy-back on the lambda's role to have the appropriate permissions?  When running locally, why aren't these picked up from AWS credentials file?
3) FindUsersByEmailAddress() doe snot work - I am getting "AmazonCognitoIdentityProviderException: The security token included in the request is invalid"

Thanks.

**Comment by sriramkumarm1** [comment]
Thanks for the kind words Igor. Really glad it helped and piqued your interest.

For the questions you've posed - 

• If you/one is planning to run the back-end in an AWS Lambda, why use the SRP and not the Admin flow? - **Because Admin flow serves a different usecase, when the solution we're designing is used for an administrative purpose, or the hosted AWS service has an admin role. In this case, since it's a user initiated API, I think SRP would be sufficient and works.**


• In the section "Prerequisites for Accessing AWS Cognito Resources" you state "In case if we're not deploying our application inside an AWS environment we'd also require the credentials of a user who has all the required permissions for accessing the Cognito user pool.". If running in an AWS Lambda, would that piggy-back on the lambda's role to have the appropriate permissions? When running locally, why aren't these picked up from AWS credentials file? - **I just wanted to mention the two ways of implementing things. When you're not deploying into AwS but are curious to know how to connect to cognito, the access keys are the go. But if you're deploying inside the AWS service, you don't need access keys itself and instead add role to the service that runs the code.**

**And for that we use another overload constructor of CognitoUser or CognitoIdentityProvider, where we don't pass these credentials. They look like below:**

**_provider = new AmazonCognitoIdentityProviderClient(RegionEndpoint.GetBySystemName(_cloudConfig.Region));            
_userPool = new CognitoUserPool(_cloudConfig.UserPoolId, _cloudConfig.AppClientId, _provider);**            

**And the role of the service has these policies:**
**Allow: cognito-idp:ListUsers**
**Allow: cognito-idp:AdminGetUser****

FindUsersByEmailAddress() doe snot work - I am getting "AmazonCognitoIdentityProviderException: The security token included in the request is invalid”

**I really need to check this one, coz it was working fine for me. I used the above mentioned policies for the service I'm running, let me know if you're using anything different.**

**Comment by referbruv** [comment]
Thanks for the kind words Igor. Really glad it helped and piqued your interest.

For the questions you've posed - 

• If you/one is planning to run the back-end in an AWS Lambda, why use the SRP and not the Admin flow? - **Because Admin flow serves a different usecase, when the solution we're designing is used for an administrative purpose, or the hosted AWS service has an admin role. In this case, since it's a user initiated API, I think SRP would be sufficient and works.**


• In the section "Prerequisites for Accessing AWS Cognito Resources" you state "In case if we're not deploying our application inside an AWS environment we'd also require the credentials of a user who has all the required permissions for accessing the Cognito user pool.". If running in an AWS Lambda, would that piggy-back on the lambda's role to have the appropriate permissions? When running locally, why aren't these picked up from AWS credentials file? - **I just wanted to mention the two ways of implementing things. When you're not deploying into AwS but are curious to know how to connect to cognito, the access keys are the go. But if you're deploying inside the AWS service, you don't need access keys itself and instead add role to the service that runs the code.**

**And for that we use another overload constructor of CognitoUser or CognitoIdentityProvider, where we don't pass these credentials. They look like below:**

```
_provider = new AmazonCognitoIdentityProviderClient(RegionEndpoint.GetBySystemName(_cloudConfig.Region));            
_userPool = new CognitoUserPool(_cloudConfig.UserPoolId, _cloudConfig.AppClientId, _provider);
```         

**And the role of the service has these policies:**
**Allow: cognito-idp:ListUsers**
**Allow: cognito-idp:AdminGetUser****

FindUsersByEmailAddress() doe snot work - I am getting "AmazonCognitoIdentityProviderException: The security token included in the request is invalid”

**I really need to check this one, coz it was working fine for me. I used the above mentioned policies for the service I'm running, let me know if you're using anything different.**

**Comment by MCAleckson** [comment]
In Visual Studio 2022 creating a Xamarin Android app, I'm implementing this code.  I too am getting an unhandled exception.

Amazon.CognitoIdentityProvider.AmazonCognitoIdentityProviderException: 'Missing Authentication Token'

This occurs when the _provider.ListUsersAsync method executes in the FindUsersByEmailAddress method.
